version: '3.9'

services:

  trip-statistics-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - HOST_DB=postgres:5432
      - NAME_DB=trip_statistics
      - USER_DB=trip_statistics
      - PASS_DB=DT123@
      - PASS_DB_ADMIN=DT123@
      - LOG_LEVEL=info
      - JAVA_OPTS=-Xms512m -Xmx4g
    networks:
      - backend
    healthcheck:
      test: "curl --fail --silent localhost:8080/api/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - NAME_DB=trip_statistics
      - PASS_DB=DT123@
    volumes:
      - ./.assets/conf/local/db:/docker-entrypoint-initdb.d/
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend: