spring:
  ## Database versioning configuration
  liquibase:
    url: jdbc:postgresql://${HOST_DB:localhost:5432}/${NAME_DB:trip_statistics}?autoReconnect=true
    user: user_${NAME_DB:trip_statistics}_admin
    password: ${PASS_DB_ADMIN:DT123@}

  datasource:
    url: jdbc:postgresql://${HOST_DB:localhost:5432}/${NAME_DB:trip_statistics}?autoReconnect=true
    username: user_${USER_DB:trip_statistics}_app
    password: ${PASS_DB:DT123@}
    driverClassName: org.postgresql.Driver

  jpa:
    database: postgresql
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 5000
          order_inserts: false
          order_updates: true
          batch_versioned_data: true
        generate_statistics: false
        cache:
          use_second_level_cache: false
        hbm2ddl:
          auto: none
