spring:
  ## Database versioning configuration
  liquibase:
    change-log: classpath:migrations/migrations-master.xml
    url: jdbc:postgresql://${HOST_DB:localhost:5432}/${NAME_DB:trip_statistics}?autoReconnect=true
    user: user_${NAME_DB:trip_statistics}_admin
    password: ${PASS_DB_ADMIN:DT123@}
  datasource:
    url: jdbc:postgresql://${HOST_DB:localhost:5432}/${NAME_DB:trip_statistics}?autoReconnect=true
    username: user_${USER_DB:trip_statistics}_app
    password: ${PASS_DB:DT123@}
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${HIKARI_MAXIMUM_POOLSIZE:20}
      leak-detection-threshold: ${HIKARI_LEAK_THRESHOLD:60000}
      max-lifetime: ${HIKARI_MAX_LIFETIME:120000}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:50000}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:false}
    open-in-view: false

server:
  servlet:
    context-path: /challenge
